project:
  type: website
  output-dir: docs

website:
  title: "Safouane Chergui"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chsafouane
      - icon: linkedin
        href: https://www.linkedin.com/in/safouane-chergui/
      - icon: cup-straw
        href: https://buymeacoffee.com/chsafouane
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: auto