project:
  type: website
  output-dir: docs

website:
  title: "Safouane Chergui"
  site-url: https://chsafouane.github.io
  description: "Just a fancy note-taking website for my notes not to die on my iPad"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chsafouane
      - icon: linkedin
        href: https://www.linkedin.com/in/safouane-chergui/
      - icon: cup-straw
        href: https://buymeacoffee.com/chsafouane
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: auto